### ISSUE TITLE
Ballots formatted with numbers

### ISSUE THREAD

**Issue by ikatza** [jontingvold/pyrankvote#4]
Hi, great project! thanks for doing this.

I ran an STV election and the outcome is a csv file with a table like this:

A | B | C
-- | -- | --
1 | 2 | 3
2 | 3 | 1
3 | 1 | 2
3 | 2 | 1
2 | 1 | 3

Is there a straightforward way in this project to use that table as input or convert it to the expected input: 

```
ballots = [
    Ballot(ranked_candidates=[A, B, C]),
    Ballot(ranked_candidates=[C, A, B]),
    Ballot(ranked_candidates=[B, C, A]),
    Ballot(ranked_candidates=[C, B, A]),
    Ballot(ranked_candidates=[B, A, C])
]
```

**Comment by ikatza** [comment]
Well I've managed to scratch my back for this one, a quick gist:
https://gist.github.com/ikatza/c4f8ad349af740787de8d13fb0f1e5f3

**Comment by jontingvold** [comment]
I'm sorry. It is not a straightforward way to convert from that table format.

I see most users of the library have formats like these, so I will put on the todo list.
